### PR TITLE
New profiles in Definitions.yaml

### PR DESCRIPTION
**Pull request by By6r9**
Added several profiles to make easier game import when emulator supports more systems.

### CODE REVIEW

**Comment by JosefNemec** [comment]
What's the point of duplicating profiles with the same configuration (GameBoy and Dolphin for example)? I'm maybe not seeing something, but for example Wii and GameCube profiles look exactly the same to me.

**Comment by By6r9** [comment]
Now:
Adding 50 Gamecube games:
Dolphin>Default> 50 items added with first (Gamecube) platform.
Adding 50 Wii games:
Dolphin>Default> 50 items added with first (Gamecube) platform. You need to click every item and change platform.

After adding profiles:
Adding 50 Gamecube games:
Dolphin>Default or Gamecube> 50 items added with first (Gamecube) or Gamecube platform.
Adding 50 Wii games:
Dolphin>Wii> 50 items added with Wii platform. 

Same problem with every other emulator/core which supports more than one platform. You need a step in import wizard with selecting platform, easy way to change platform for multiple items or both those things.

**Comment by JosefNemec** [comment]
I understand and it makes sense to me if the extension support is different based on platform for example. Otherwise I would rather add improvements mentioned in #423 then duplicate entries in emulator definitions.

**Comment by By6r9** [comment]
Removed unnecessary extensions.

**Comment by JosefNemec** [comment]
I still don't like how we would have duplicate records only to separate them by platform. I fully understand that usability of current import dialog is not ideal, but we should fix that (via #423), instead of introducing these workarounds.

**Comment by By6r9** [comment]
Fine with me, this PR is more of a band-aid, and other solution would release me from writing subprofiles for mednafen and bizhawk.

**Comment by JosefNemec** [comment]
I'm willing to merge this if you make some changes:

* Remove duplicated entries. For example you created new Wii and GameCube profiles, but kept the one that contains both platforms. Just remove the original profile that contains all platforms and keep separate ones.
* Make sure that separate profiles only have file extensions supported by that platform.

**Comment by By6r9** [comment]
- removed
- duplicate extension are either archives, or generic extensions (.bin, for example). For consoles there are usually only one or two typical extension per platforms. Ping me here, or on discord if I should double-check something.

**Pull request merged**
