### PR TITLE
Bug fix:  Playnite displays an error during computer shutdown (#866)

### LINKED ISSUE #866: Application hangs during shutdown
I leave Playnite running in the background at all times, and when I shut down my PC, the shutdown doesn't happen as Playnite hangs and needs user input to continue. This happens every single shutdown.
img_20181211_153654

Additionally, it would be nice if the application would remember your last position between sessions, and if it could be launched minimized to tray, without needing to enable "minimize to tray."

### PR DESCRIPTION
**Pull request by craigt00**
Fixes #866 

As discussed, I've added a condition into Application_SessionEnding which stops Playnite from attempting to release it's unmanaged resources (including CefSharp) if the computer is shutting down.  The current user logging off will continue to clean up resources as usual and this doesn't trigger the bug to occur.

As a side note, I did attempt to upgrade to the latest stable version of CefSharp (73.1.130) but this didn't fix the issue.  Therefore, since I'm not clear on the wider impact of updating CefSharp I've reverted this change in this pull request.

### CODE REVIEW

**Comment by JosefNemec** [comment]
I don't like that you are completely skipping release of all resources. We should only skip CefSharp stuff if that's the issue. Everything else should still be released/disposed properly.

**Comment by craigt00** [comment]
Agreed.  I've refactored the solution so the condtional is now in the CefTools class.  How do you feel about that?

**Comment by JosefNemec** [comment]
I don't like this approach either (I don't think that use static property in this scenario is appropriate). Why not just add argument to `ReleaseResources` that would skip disposal of CefSharp? You can then replace `Quit` call in shutdown handler with that (and also call app shutdown since you would not be using Quit anymore).

**Comment by JosefNemec** [comment]
I fixed it in 86e2ebbfdd2f34463a3ec1a06c50b2269a7f327a

**Comment by craigt00** [comment]
Thanks @JosefNemec.  Apologies for the (very) late response.  My work IRL has consumed a lot of my time over the last few weeks.

**Pull request closed without merging**
