### PR TITLE
Separate account linking settings from uninstalled games import

### PR DESCRIPTION
**Pull request by T-0pel**
Issue #1227.

Modified the settings for all plugin libraries supporting the uninstalled games import. Users can now synchronize their game stats without having to import uninstalled games. Added Czech translation of the button text, for other languages I would have to use Google Translate.

I am used to doing code cleanup on classes that I work with, but I do realize that it makes the PR harder to follow. Let me know if this is ok or you would prefer for me to leave the other parts of the class intact.

I wanted to add unit tests, but they would require at least some refactor and the PR is already large enough without it. I can add them as separate issue/PR if you don't mind.

### CODE REVIEW

**Comment by T-0pel** [comment]
@JosefNemec Hi, did you get a chance to look at this PR? I can modify it or recreate it without the code cleanup if you want.

**Comment by JosefNemec** [comment]
Sorry it took me so long to get to it, I'm not feeling very well lately. Anyways I only checked how it looks like in the application and I think it's ok.

Please remove the refactoring/cleaup changes since it makes it so much harder to review the code. You can open separate PR for it later.

Also don't make changes to localization files in repository, they will not get pushed to Crowding and will be overwritten once I do push from Crowdin to GitHub. Only original English source file should be updated. Translated string should be only updated via Crowdin.

**Comment by T-0pel** [comment]
No worries, I hope you feel better soon @JosefNemec!

I removed the code cleanup, I only left fixed typos and removed unnecessary spaces. I removed the Czech localization as well. It is still a lot of changes because I had to change each supported plugin.

As another PR, It could help to create some parent class for plugins that allow account connection. Something like "LibraryPluginWithAccount" that inherits from "LibraryPlugin" which will implement the GetGames method with settings from a new settings class "LibraryWithAccountSettings". This will limit code duplication and it would also make it easier to write unit tests for this functionality. Please let me know if you think that makes sense, otherwise, I will take a look at some other issue.

**Comment by JosefNemec** [comment]
Sorry for no response for such a long time. I will be merging this to Playnite 6 once I start working on it (very soon).

**Comment by T-0pel** [comment]
Cool, I understand, I also did not have much time during the summer. Let me know if there is anything else you want to me to change. I will take a look at #826 this week.

**Comment by JosefNemec** [comment]
I merged this manually into `devel6`.

**Pull request closed without merging**
