### PR TITLE
Add humblebundle support (in progress)

### PR DESCRIPTION
**Pull request by djeebus**
Hey all, thought I'd take a stab at implementing a humblebundle plugin. There are a few things that are a little wonky, still working on it, but thought I'd push it out to get some feedback.

Things that work:
- authenticating via browser
- pulling back your list of games, filtered by the windows platform
- lists links to download the game, the torrent, or go to the dev website

Things that are a little wonky:
- clicking "Install" launches a browser to download the file
- "Install" changes to "Installing", doesn't revert back to "Install"
- no way to identify if the game is installed or not

Things I'd still like to implement:
- generate and/or redeem steam keys
- generate and/or redeem uplay keys
- tests!

The API/UI of Playnite clearly wasn't intended to be used like this, but it would be super useful to be able to see humble bundle stuff in the same UI as my steam/uplay/epic/etc libraries. I might try to squeeze a slightly better UI in here somewhere (maybe some toggles to show "Download" instead of "Install", or a "Browse" button to manually identify the install location?)

Thanks for all the work done so far!

### CODE REVIEW

**Comment by JosefNemec** [comment]
Cool, let me know when this is in state to be reviewed.

Also for the future, I would recommend commenting in the original issue that you are going to work on it (as stated in contribution guidelines) to make sure that other people are not already working on it. Original issue is #112

I've also added [some notes](https://github.com/JosefNemec/Playnite/issues/112#issuecomment-456159025) to that original issue not a long time ago, you might take them into consideration when working on this.

**Comment by ryanizer** [comment]
Any progress on Humble Bundle integration?

**Comment by JosefNemec** [comment]
If @djeebus is no longer working on it then I'll take a stab at it after #1135 is done.

**Comment by JosefNemec** [comment]
I'm going to close this since there doesn't seem to be any progress on it and I'll be implementing it for Playnite 7.

**Pull request closed without merging**
