### PR TITLE
Add Galaxy 2.0, IGDB, New Steam UI, EGS and Twitch Aspect ratio presets for Grid View

### PR DESCRIPTION
**Pull request by darklinkpower**

### CODE REVIEW

**Comment by JosefNemec** [comment]
Please do not separate functionality and related localization strings with different PRs, it doesn't make sense. All the changes necessary for the changes should be in the same PR.

**Comment by JosefNemec** [comment]
Also I don't see a point of 1:1 preset, you can easily add that manually. The whole point of preset is for the ratios that can't be easily calculated or are known.

**Comment by darklinkpower** [comment]
Got it, sorry I'm still figuring how Github works. I agree that it can easily be added manualy, although maybe I saw a point in adding it more for easiness than for it being difficult to figure out, but I deleted it just now, let me know if there's something else that should be fixed.

**Comment by darklinkpower** [comment]
Found a small bug that prevents the Galaxy 2.0 and Epic Games Store aspect ratio (171:241) to be used at least manually; any value higher than 100 can't be used, it gets reverted to the previous value.

**Comment by darklinkpower** [comment]
I modified the max value to 350 in both fields in case another aspect ratio gets added in the future, the highest number right now should  be 241 for the GOG2 preset, but while not added, the Origin aspect ratio is 231:326

**Comment by JosefNemec** [comment]
Just two things:
- `MaxValue` on num boxes. Please change it to 999, so we don't have to rise it again in future :)
- I think we should not bundle together multiple store options. For example if in future GOG decides to change the format, then we would have to change  a lot of things as opposed to just adjusting aspect values.

**Comment by darklinkpower** [comment]
Got it, increased values.
For point 2, do you mean separating presets by individual stores even if they share the same aspect ratio? If it's that, I agree, I modified the files to have them individually.

**Pull request merged**
