### PR TITLE
updated italian

### PR DESCRIPTION
**Pull request by StarFang208**
I added some missing lines and edited some translations.

### CODE REVIEW

**Comment by tesivo** [comment]
I think you made a mistake indicating the path to the file. It was supposed to be: source/PlayniteUI/Localization/italian.xaml

**Comment by StarFang208** [comment]
I didn't know how to modify the file in the branch, so I created another commit.
As usual of my lack of knowledge of the Git platform, I cannot change the path you suggested because the files have the same name.
What I have to do to merge the two files?

**Comment by JosefNemec** [comment]
You can edit and create changes directly from GitHub's interface if you don't have experience with Git, see https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by JosefNemec** [comment]
I'm closing this for now, please open new pull request with correct file paths.

**Pull request closed without merging**
