### PR TITLE
Update german localization

### PR DESCRIPTION
**Pull request by PhrozenByte**
~~**:construction: This is work in progress, don't merge it yet!**~~

There are some untranslatable strings (testing with Playnite 4.1):

* "SDK Documentation" in main menu
* "Extensions -> Export Library" in main menu
* "Prefer game screenshot" option in settings window ("Steam" section) + its tooltip
* "Not Played" right after the "play time" input (not in the "game progress" dropdown, `LOCNotPlayed` is used just there and not for "play time")
* The `MetaSkipNonEmptyTooltip` language variable doesn't require a `LOC` prefix
* Fullscreen Mode: Sort by "Most played"

Some questions:

* The `LOCAdvanced`, `LOCScripts`, `LOCPlugins`, `LOCReloadScriptsSuccess` language variables don't seem to be used anywhere?
* Where are the `LOCCancelMonitoring*` language variables used? I'd assume they show up when editing a game that's currently running, but this doesn't seem to be the case?

@JosefNemec 

ref #385

### CODE REVIEW

**Comment by PhrozenByte** [comment]
Great, I've updated the langauge files to 0abd92c

Some more questions:

1. Is it intentional that columns and rows are mixed up here (key vs. value)? https://github.com/JosefNemec/Playnite/blob/b9654e4a34a1c16ffb98feb2f169ede4128d3ab0/source/PlayniteUI/Localization/english.xaml#L258-L259

2. There's still no language variable for "Extensions -> Export Library" in Playnite's main menu

3. The `MetaSkipNonEmptyTooltip` language variable doesn't require a `LOC` prefix

**Comment by JosefNemec** [comment]
1) not that's not intentional, I'll fix that.
2) it's from script extension and they don't support localizations.
3) that's a bug

**Comment by PhrozenByte** [comment]
Updated to f5b6aeea66c0b3e5ff1ca23c9bd66a2dd7c386e7

This should be mergeable now, however, if you're planning to update more language variables before releasing Playnite 4.1, I'd prefer not to merge it yet and wait until just before the next release.

**Comment by PhrozenByte** [comment]
As pointed out by https://github.com/JosefNemec/Playnite/issues/385#issuecomment-387567512 there's one more untranslatable string: When grouping games by category, games without a category are shown in the "No Category" category. The "No Category" string isn't translatable.

**Comment by PhrozenByte** [comment]
@JosefNemec: Please don't forget that this PR has been merged into `devel` rather than `master`, as requested in https://github.com/JosefNemec/Playnite/issues/385#issuecomment-384635609 (at least that's what I thought you meant by "take these files from devel branch as your base", after reading it again I'm not so sure anymore). Since you're working on `master` now, I'm not sure whether this was right or not... Should I open new PRs against `master` or `devel`?

**Comment by JosefNemec** [comment]
I merged it manually

**Pull request merged**
