### PR TITLE
Term Changes to Steam links and one more added

### PR DESCRIPTION
**Pull request by darklinkpower**
Proposed changes
`Forums` -> `Community Hub`
`Discussions` (I added this one)
`Store` -> `Store Page`
`Wiki` -> `PCGamingWiki`

### CODE REVIEW

**Comment by JosefNemec** [comment]
Did you make sure this is unified across all other plugins? It doesn't make sense to me to rename it only for Steam.

**Comment by darklinkpower** [comment]
I checked all the other ones after I made the PR and to my surprise they were all named exactly PCGamingWiki already, it was just the steam plugin that wasn't. 

The only thing that wouldn't be unified would be the term `Store Page` because I'm unsure if it should be changed in all the other ones, if you are fine with it I can make the term change in the other ones too.

**Comment by JosefNemec** [comment]
It should be unified across all of them. If it points to store page then why should we call it differently for different stores?

**Comment by darklinkpower** [comment]
I made PR to the GOG (#1422), Origin (#1421) and Itchio (#1420 ) libraries to change the term "Store" to "Store Page", that way it will be unified.

**Pull request merged**
