### PR TITLE
Sync PlayTime and LastPlayed from Origin #1140

### PR DESCRIPTION
**Pull request by tylerszabo**
Implements #1140

### CODE REVIEW

**Comment by vogler** [comment]
Is this supposed to work in Playnit 5.8?
For me it doesn't import times.
(It also doesn't import uninstalled games from Origin, but that's another issue.)

**Comment by JosefNemec** [comment]
It only works if you have import of uninstalled games enabled and you are authenticated.

**Comment by vogler** [comment]
image
Not for me.

**Comment by JosefNemec** [comment]
Do you have some time already recorded for those games? Playnite will only download play time if none was recorded yet (if it's set to 0) or if "Force sync play time" is enabled.

**Comment by vogler** [comment]
I didn't, but the issue somehow resolved itself. It now shows uninstalled and time played. 👍 
I guess the [feature table](https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider) should be updated for Origin.

What's the reason for an option 'Force sync play time' and it not being the default? Shouldn't launching a game through Playnite always also update the time played recorded by Origin/others?

Another strange issue: 'Completion Status' only shows 'Played' for installed Origin games (not started) - for uninstalled games with 'Time Played' it's 'Not Played'. For Steam games it's the other way around ('Not Played' for installed, 'Played' for uninstalled).

**Comment by JosefNemec** [comment]
Some games do not launch though official launcher. Mainly older EA games (Sim City 4, Mass Effect for example) will start directly without launching Origin first (it's not something we control, we just launch the executable and if Origin is required it will be opened automatically). That's why it's not enabled by default

Please open the completion status thing as different issue.

**Comment by vogler** [comment]
Opened #1457.

Maybe it's not worth the effort, but if one would store the time from the server separately, one could check after playing if it changed, and if not add it to the local time. 'Time Played' would then always be the sum of server and local time.
Alternatively, is there a way of forcing a launch through the launcher (or maybe it's enough to have an option to always open the launcher before starting a game)?

**Pull request merged**
