### PR TITLE
Enable selecting monochrome tray icons (#1155)

### PR DESCRIPTION
**Pull request by tylerszabo**
Implements #1155

As this is my first change to the core code I expect and welcome any feedback. Thanks for taking the time to look at this; and thank you for accepting my build changes that allowed me to get here. 🙂

### CODE REVIEW

**Comment by tylerszabo** [comment]
Here's a screenshot of the settings menu. Note: no additional localized strings required ;)

image

**Comment by tylerszabo** [comment]
Resolved merge conflicts

**Comment by JosefNemec** [comment]
I think it would be better to remove the drop shadow from tray icon (create different icon file specifically for tray) and make it contrast more with taskbar background. Also what is the black one for?

**Comment by tylerszabo** [comment]
Good idea, I'll take another pass at the icon. The black icon was for users of [Windows Light Theme](https://blogs.windows.com/windowsexperience/2018/11/14/announcing-windows-10-insider-preview-build-18282/).

**Comment by tylerszabo** [comment]
The look without drop shadow:

image

**Pull request merged**
